# -*- coding: utf-8 -*-
"""Calculadora formula de Bozemann

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VhFCaRDXZl5bhS8AZCd-mYA3BOwDWMQa
"""

import math

"""El siguiente codigo tiene como proposito operar la formula de entropia propuesta por Boltzmann, cabe aclarar que el sistema maneja una magnitudes realistas (las que se manejan en ejercicios basicos de formula de boltzmann es decir una entropia desde el orden de 10e-21 a 10e-24), Si se intenta calcular un valor demasiado grande o pequeño se generara un error propio de la libreria con la que se trabaja, tenga en cuenta usar punto y no coma, y a su vez escribir tal cual lo que se desea calcular "microestados compatibles con el macroestado" o "entropia" se recomiendo copiar y pegar para evitar errores"""

k = 1.380649e-23
que_se_desea_calcular = input("¿Desea calcular entropia o el numero de microestados compatibles con el macroestado? ")
if que_se_desea_calcular == "entropia":
    microestados = float(input("¿Cuántos microestados compatibles tiene el macroestado? "))
    S = k * math.log(microestados)
    print("el valor de la entropia es",S, "KJ/K")
elif que_se_desea_calcular == "microestados compatibles con el macroestado":
    S = float(input("¿Cual es el valor de la entropia en J/K? (Use 'e' para la notacion cientifica, por ejemplo: 4.0e-23): "))
    microestados = math.exp(S / k)
    print(microestados)
else:
    print("Ingrese una opcion valida, ya sea entropia o microestados compatibles con el macroestado.")
